# Generated by Django 5.2.17 on 2026-09-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assessments',
            index=models.Index(fields=['cohort', 'published', 'start_at', 'end_at'], name='idx_assessment_cohort_window'),
        ),
        migrations.AddIndex(
            model_name='assessmentsubmissions',
            index=models.Index(fields=['assessment', 'submitted_at'], name='idx_assessment_submission_at'),
        ),
        migrations.AddIndex(
            model_name='mileagetransactions',
            index=models.Index(fields=['user', '-created_at'], name='idx_mileage_user_created'),
        ),
        migrations.AddIndex(
            model_name='notices',
            index=models.Index(fields=['cohort', '-created_at'], name='idx_notice_cohort_created'),
        ),
        migrations.AddIndex(
            model_name='purchaserequests',
            index=models.Index(fields=['cohort', 'status', '-created_at'], name='idx_purchase_cohort_status'),
        ),
        migrations.AddIndex(
            model_name='schedulednotices',
            index=models.Index(fields=['is_active', 'next_publish_at'], name='idx_scheduled_due'),
        ),
    ]
