# Generated by Django 5.2.17 on 2026-09-23 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_jobs_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyDocuments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_key', models.TextField(unique=True)),
                ('source_type', models.CharField(max_length=32)),
                ('source_name', models.TextField()),
                ('source_url', models.TextField(blank=True, default='')),
                ('storage_key', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policy_documents',
                'indexes': [models.Index(fields=['is_active', 'source_type'], name='idx_policy_active_type')],
            },
        ),
        migrations.CreateModel(
            name='PolicyDocumentRevisions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('revision_no', models.PositiveIntegerField()),
                ('content_sha256', models.CharField(max_length=64)),
                ('extracted_text', models.TextField()),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('extraction_metadata', models.JSONField(default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='lms.policydocuments')),
            ],
            options={
                'db_table': 'policy_document_revisions',
                'indexes': [models.Index(fields=['document', '-revision_no'], name='idx_policy_document_latest')],
                'constraints': [models.UniqueConstraint(fields=('document', 'revision_no'), name='uq_policy_document_revision')],
            },
        ),
    ]
