# Generated by Django 5.2.17 on 2026-09-24 08:39

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_study_note_generation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGithubOwners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField()),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'study_github_owners',
            },
        ),
        migrations.CreateModel(
            name='StudyPracticeJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(choices=[('note', 'Note'), ('file', 'File')])),
                ('label', models.CharField(default='')),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='running')),
                ('message', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'study_practice_jobs',
            },
        ),
        migrations.CreateModel(
            name='StudyPracticeRuns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('schedule', 'Schedule'), ('manual', 'Manual')], default='schedule')),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='running')),
                ('problems', models.PositiveIntegerField(default=0)),
                ('dates', models.JSONField(default=list)),
                ('message', models.TextField(default='')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'study_practice_runs',
            },
        ),
        migrations.CreateModel(
            name='StudyPracticeSettings',
            fields=[
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='lms.studysources')),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'study_practice_settings',
            },
        ),
        migrations.CreateModel(
            name='StudyTutorTurns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_key', models.CharField()),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')])),
                ('text', models.TextField()),
                ('kind', models.CharField(default='')),
                ('hint_level', models.IntegerField(blank=True, null=True)),
                ('lines', models.JSONField(default=list)),
                ('llm', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'study_tutor_turns',
            },
        ),
        migrations.RemoveConstraint(
            model_name='practiceproblems',
            name='ck_practice_problem_kind',
        ),
        migrations.AddField(
            model_name='practicesets',
            name='origin',
            field=models.CharField(choices=[('lesson', 'lesson'), ('note', 'note'), ('file', 'file')], default='lesson'),
        ),
        migrations.AddField(
            model_name='practicesets',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_practice_sets', to='lms.users'),
        ),
        migrations.AlterField(
            model_name='practiceproblems',
            name='kind',
            field=models.CharField(choices=[('concept', 'Concept'), ('code_output', 'Code Output'), ('code_blank', 'Code Blank'), ('code_fix', 'Code Fix'), ('code_write', 'Code Write'), ('code_scratch', 'Code Scratch')]),
        ),
        migrations.AddConstraint(
            model_name='practiceproblems',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('concept', 'code_output', 'code_blank', 'code_fix', 'code_write', 'code_scratch'))), name='ck_practice_problem_kind'),
        ),
        migrations.AddConstraint(
            model_name='practicesets',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ('lesson', 'note', 'file'))), name='ck_practice_set_origin'),
        ),
        migrations.AddField(
            model_name='studygithubowners',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.users'),
        ),
        migrations.AddField(
            model_name='studygithubowners',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.cohorts'),
        ),
        migrations.AddField(
            model_name='studypracticejobs',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.cohorts'),
        ),
        migrations.AddField(
            model_name='studypracticejobs',
            name='practice_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.practicesets'),
        ),
        migrations.AddField(
            model_name='studypracticejobs',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.users'),
        ),
        migrations.AddField(
            model_name='studypracticeruns',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.studysources'),
        ),
        migrations.AddField(
            model_name='studypracticesettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.users'),
        ),
        migrations.AddField(
            model_name='studytutorturns',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.practiceproblems'),
        ),
        migrations.AddField(
            model_name='studytutorturns',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.users'),
        ),
        migrations.AddConstraint(
            model_name='studygithubowners',
            constraint=models.UniqueConstraint(models.F('cohort'), django.db.models.functions.text.Lower('owner'), name='uq_study_github_cohort_owner'),
        ),
        migrations.AddIndex(
            model_name='studypracticejobs',
            index=models.Index(fields=['user', '-created_at'], name='idx_study_job_user_created'),
        ),
        migrations.AddConstraint(
            model_name='studypracticejobs',
            constraint=models.CheckConstraint(condition=models.Q(('origin__in', ('note', 'file'))), name='ck_study_job_origin'),
        ),
        migrations.AddConstraint(
            model_name='studypracticejobs',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('running', 'done', 'failed'))), name='ck_study_job_status'),
        ),
        migrations.AddIndex(
            model_name='studypracticeruns',
            index=models.Index(fields=['source', '-started_at'], name='idx_study_run_source_started'),
        ),
        migrations.AddConstraint(
            model_name='studypracticeruns',
            constraint=models.CheckConstraint(condition=models.Q(('trigger__in', ('schedule', 'manual'))), name='ck_study_run_trigger'),
        ),
        migrations.AddConstraint(
            model_name='studypracticeruns',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('running', 'done', 'failed'))), name='ck_study_run_status'),
        ),
        migrations.AddIndex(
            model_name='studytutorturns',
            index=models.Index(fields=['user', 'thread_key', 'id'], name='idx_study_turn_thread'),
        ),
        migrations.AddConstraint(
            model_name='studytutorturns',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ('user', 'assistant'))), name='ck_study_turn_role'),
        ),
    ]
