# Generated by Django 5.2.17 on 2026-09-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_integrate_practice_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumes',
            name='source_tailored_resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_resumes', to='lms.resumes'),
        ),
        migrations.CreateModel(
            name='ResumeTailorings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_snapshot_hash', models.CharField(default='')),
                ('source_resume_hash', models.CharField(default='')),
                ('company_name', models.CharField(default='')),
                ('job_title', models.CharField(default='')),
                ('review_session', models.JSONField(default=dict)),
                ('review_progress', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tailoring', to='lms.resumes')),
            ],
            options={
                'db_table': 'resume_tailorings',
                'constraints': [models.CheckConstraint(condition=models.Q(('review_progress__in', ('not_started', 'in_progress', 'completed'))), name='ck_resume_tailoring_progress')],
            },
        ),
    ]
