# Generated by Django 6.1.1 on 2026-09-30 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_resume_tailorings'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceissuereports',
            name='external_response_id',
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PresenceChecks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField()),
                ('period', models.CharField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_by', models.ForeignKey(blank=True, db_column='checked_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presence_checks', to='lms.users')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.cohorts')),
            ],
            options={
                'db_table': 'presence_checks',
            },
        ),
        migrations.CreateModel(
            name='PresenceCheckItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField()),
                ('reason', models.CharField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.users')),
                ('presence_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lms.presencechecks')),
            ],
            options={
                'db_table': 'presence_check_items',
            },
        ),
        migrations.CreateModel(
            name='AlertPopupTargets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='lms.alertpopups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.users')),
            ],
            options={
                'db_table': 'alert_popup_targets',
                'indexes': [models.Index(fields=['user'], name='alert_popup_user_id_a619be_idx')],
                'constraints': [models.UniqueConstraint(fields=('popup', 'user'), name='uq_alert_popup_target')],
            },
        ),
        migrations.AddIndex(
            model_name='presencechecks',
            index=models.Index(fields=['cohort', 'checked_at'], name='presence_ch_cohort__d98146_idx'),
        ),
        migrations.AddConstraint(
            model_name='presencechecks',
            constraint=models.CheckConstraint(condition=models.Q(('period__in', ('am', 'pm'))), name='ck_presence_check_period'),
        ),
        migrations.AddConstraint(
            model_name='presencecheckitems',
            constraint=models.UniqueConstraint(fields=('presence_check', 'user'), name='uq_presence_check_item'),
        ),
        migrations.AddConstraint(
            model_name='presencecheckitems',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('present', 'absent'))), name='ck_presence_check_item_state'),
        ),
    ]
