# Generated by Django 6.1.1 on 2026-09-30 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_manager_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertpopups',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AlertPopupReads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField()),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='lms.alertpopups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.users')),
            ],
            options={
                'db_table': 'alert_popup_reads',
                'constraints': [models.UniqueConstraint(fields=('popup', 'user'), name='uq_alert_popup_read')],
            },
        ),
    ]
