# Generated by Django 5.2.17 on 2026-09-30 05:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_submission_task_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeExperiences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('project', 'Project'), ('employment', 'Employment'), ('education', 'Education'), ('activity', 'Activity'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('period_text', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_experiences', to='lms.users')),
            ],
            options={
                'db_table': 'resume_experiences',
            },
        ),
        migrations.CreateModel(
            name='ResumeExperienceBindings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_key', models.CharField(max_length=80)),
                ('field_path', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_bindings', to='lms.resumes')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resume_bindings', to='lms.resumeexperiences')),
            ],
            options={
                'db_table': 'resume_experience_bindings',
            },
        ),
        migrations.CreateModel(
            name='ResumeEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fact_type', models.CharField(max_length=32)),
                ('normalized_fact', models.TextField()),
                ('evidence_quote', models.TextField()),
                ('source_type', models.CharField(choices=[('resume_text', 'Resume text'), ('user_answer', 'User answer'), ('uploaded_document', 'Uploaded document')], max_length=24)),
                ('source_id', models.CharField(max_length=255)),
                ('assertion_state', models.CharField(choices=[('resume_stated', 'Resume stated'), ('user_asserted', 'User asserted'), ('uncertain', 'Uncertain'), ('contradicted', 'Contradicted'), ('retracted', 'Retracted'), ('superseded', 'Superseded')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conflicts_with_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conflicting_reports', to='lms.resumeevidence')),
                ('supersedes_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='lms.resumeevidence')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='lms.resumeexperiences')),
            ],
            options={
                'db_table': 'resume_evidence',
            },
        ),
        migrations.AddIndex(
            model_name='resumeexperiences',
            index=models.Index(fields=['user', 'status'], name='resume_expe_user_id_c843b5_idx'),
        ),
        migrations.AddIndex(
            model_name='resumeexperiencebindings',
            index=models.Index(fields=['resume', 'experience'], name='resume_expe_resume__35f634_idx'),
        ),
        migrations.AddConstraint(
            model_name='resumeexperiencebindings',
            constraint=models.UniqueConstraint(fields=('resume', 'item_key'), name='uq_resume_experience_item'),
        ),
        migrations.AddIndex(
            model_name='resumeevidence',
            index=models.Index(fields=['experience', 'assertion_state'], name='resume_evid_experie_d3cb62_idx'),
        ),
    ]
