# Generated by Django 5.2.17 on 2026-09-30 06:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_resume_experience_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('role_context_id', models.CharField(blank=True, max_length=255, null=True)),
                ('target_snapshot', models.JSONField(default=dict)),
                ('entry_source', models.CharField(choices=[('resume_first', 'resume_first'), ('job_first', 'job_first'), ('manual', 'manual')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('in_progress', 'in_progress'), ('ready', 'ready'), ('submitted', 'submitted'), ('archived', 'archived')], default='draft', max_length=20)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_resume', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='lms.resumes')),
                ('carried_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.applications')),
                ('requirement_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.jobrequirementprofiles')),
                ('tailored_resume', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_workspace', to='lms.resumes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lms.users')),
            ],
            options={
                'db_table': 'applications',
                'indexes': [models.Index(fields=['user', 'status'], name='ix_application_user_status')],
                'constraints': [models.UniqueConstraint(fields=('user', 'idempotency_key'), name='uq_application_request'), models.CheckConstraint(condition=models.Q(('id', models.F('carried_from_id')), _negated=True), name='ck_application_not_self'), models.CheckConstraint(condition=models.Q(('entry_source__in', ['resume_first', 'job_first', 'manual'])), name='ck_application_entry'), models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'in_progress', 'ready', 'submitted', 'archived'])), name='ck_application_status'), models.CheckConstraint(condition=models.Q(('base_resume', models.F('tailored_resume')), _negated=True), name='ck_application_distinct_resume')],
            },
        ),
    ]
