# Generated by Django 5.2.17 on 2026-09-30 08:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0012_application_workspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationPlans',
            fields=[
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='planning_record', serialize=False, to='lms.applications')),
                ('input_hash', models.CharField(max_length=64)),
                ('version', models.CharField(max_length=32)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'application_plans',
            },
        ),
        migrations.CreateModel(
            name='ApplicationQuestions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('raw_text', models.TextField()),
                ('character_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('count_unit', models.CharField(choices=[('characters', 'Characters'), ('bytes', 'Bytes'), ('unknown', 'Unknown')], default='characters', max_length=16)),
                ('include_spaces', models.BooleanField(blank=True, null=True)),
                ('source_type', models.CharField(max_length=24)),
                ('source_reference', models.CharField(blank=True, default='', max_length=255)),
                ('import_key', models.CharField(max_length=64)),
                ('analysis', models.JSONField(default=dict)),
                ('analysis_version', models.CharField(blank=True, max_length=32, null=True)),
                ('analysis_input_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lms.applications')),
            ],
            options={
                'db_table': 'application_questions',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAnswers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_key', models.CharField(default='draft', max_length=128)),
                ('content', models.TextField()),
                ('source_type', models.CharField(choices=[('user_draft', 'User draft'), ('user_supplement', 'User supplement'), ('ai_generated', 'Future AI output')], default='user_draft', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=20)),
                ('confirmation_key', models.CharField(blank=True, default='', max_length=64)),
                ('topic_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lms.resumeexperiences')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lms.applicationquestions')),
            ],
            options={
                'db_table': 'application_answers',
            },
        ),
        migrations.AddConstraint(
            model_name='applicationquestions',
            constraint=models.UniqueConstraint(fields=('application', 'import_key'), name='uq_application_question_import'),
        ),
        migrations.AddConstraint(
            model_name='applicationquestions',
            constraint=models.CheckConstraint(condition=models.Q(('character_limit__isnull', True), ('character_limit__gt', 0), _connector='OR'), name='ck_application_question_limit'),
        ),
        migrations.AddConstraint(
            model_name='applicationquestions',
            constraint=models.CheckConstraint(condition=models.Q(('count_unit__in', ['characters', 'bytes', 'unknown'])), name='ck_application_question_unit'),
        ),
        migrations.AddConstraint(
            model_name='applicationanswers',
            constraint=models.UniqueConstraint(fields=('question', 'answer_key'), name='uq_application_answer_key'),
        ),
    ]
