# Generated by Django 5.2.17 on 2026-10-01 00:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_application_questions_answers'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE jobs.jobs ADD COLUMN apply_method varchar(16) NULL; "
            "ALTER TABLE jobs.jobs ADD CONSTRAINT ck_job_apply_method "
            "CHECK (apply_method IS NULL OR apply_method IN ('HOMEPAGE','SITE','EMAIL','OTHER'));",
            "ALTER TABLE jobs.jobs DROP CONSTRAINT ck_job_apply_method; "
            "ALTER TABLE jobs.jobs DROP COLUMN apply_method;",
        ),
        migrations.CreateModel(
            name='CompanyProfiles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_key', models.CharField(max_length=255, unique=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_type', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('homepage_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_profiles',
            },
        ),
        migrations.CreateModel(
            name='RecruitRoles',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=120)),
                ('role_name', models.CharField(max_length=255)),
                ('role_description', models.TextField()),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('questions', models.JSONField(blank=True, default=list)),
                ('content_hash', models.CharField(max_length=64)),
                ('source_type', models.CharField(choices=[('company_site', 'Official'), ('other', 'Private')], max_length=20)),
                ('source_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_status', models.CharField(default='unverified', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_owner', models.CharField(default='', editable=False, max_length=32)),
                ('use_count', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recruit_roles', to='lms.companyprofiles')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recruit_roles', to='lms.users')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_recruit_roles', to='lms.users')),
            ],
            options={
                'db_table': 'recruit_roles',
                'constraints': [models.UniqueConstraint(condition=models.Q(('source_type', 'company_site')), fields=('company', 'season', 'role_name', 'content_hash'), name='uq_recruit_role_official'), models.UniqueConstraint(condition=models.Q(('source_type', 'other')), fields=('company', 'season', 'role_name', 'content_hash', 'dedupe_owner'), name='uq_recruit_role_private'), models.CheckConstraint(condition=models.Q(('verification_status__in', ['unverified', 'verified', 'rejected'])), name='ck_recruit_role_verification'), models.CheckConstraint(condition=models.Q(models.Q(('dedupe_owner', ''), ('source_type', 'company_site')), models.Q(('source_type', 'other'), models.Q(('dedupe_owner', ''), _negated=True)), _connector='OR'), name='ck_recruit_role_scope')],
            },
        ),
    ]
