# Generated by Django 6.1.1 on 2026-10-08 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_cohort_deletion_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitRoleReports',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='lms.recruitroles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruit_role_reports', to='lms.users')),
            ],
            options={
                'db_table': 'recruit_role_reports',
                'constraints': [models.UniqueConstraint(fields=('role', 'user'), name='uq_recruit_role_report_once'), models.CheckConstraint(condition=models.Q(('reason__in', ['other_company', 'wrong', 'past_season'])), name='ck_recruit_role_report_reason')],
            },
        ),
    ]
