// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd6amu1653Fc071OYeI_Fjfi6hMQvNih8',
    appId: '1:737679563447:web:9c0a512bc37811f48bcb32',
    messagingSenderId: '737679563447',
    projectId: 'skn34-3rd-2team',
    authDomain: 'skn34-3rd-2team.firebaseapp.com',
    storageBucket: 'skn34-3rd-2team.firebasestorage.app',
    measurementId: 'G-R9W8L84Q2K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTjWQxkJpntmMNbvsEzZZJ4DSFPddKInw',
    appId: '1:737679563447:android:c08172132e8b68848bcb32',
    messagingSenderId: '737679563447',
    projectId: 'skn34-3rd-2team',
    storageBucket: 'skn34-3rd-2team.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd6amu1653Fc071OYeI_Fjfi6hMQvNih8',
    appId: '1:737679563447:web:8e02f32dcee1167b8bcb32',
    messagingSenderId: '737679563447',
    projectId: 'skn34-3rd-2team',
    authDomain: 'skn34-3rd-2team.firebaseapp.com',
    storageBucket: 'skn34-3rd-2team.firebasestorage.app',
    measurementId: 'G-TT0BCGGZK2',
  );
}
