-- Same RDS as LMS. Schema name: jobs.
-- 1:1 with job_matching_bot/ingestion/sqlite_store.py
-- TEXT timestamps -> timestamptz, JSON strings -> jsonb, 0/1 -> boolean, AUTOINCREMENT -> identity.
-- deadline/posted_at stay varchar (listing text is not always a date).
-- Apply: CREATE SCHEMA IF NOT EXISTS jobs. Then SET search_path TO jobs and run this file.

CREATE TABLE IF NOT EXISTS jobs (
    job_id varchar PRIMARY KEY,
    source varchar,
    source_job_id varchar,
    source_url varchar,
    company varchar,
    company_type varchar,
    title varchar,
    description text,
    required_skills jsonb NOT NULL DEFAULT '[]'::jsonb,
    preferred_skills jsonb NOT NULL DEFAULT '[]'::jsonb,
    career_type varchar,
    min_career_years integer,
    education varchar,
    region varchar,
    employment_type varchar,
    posted_at varchar,
    deadline varchar,
    status varchar,
    content_hash varchar,
    parser_version varchar,
    field_provenance jsonb NOT NULL DEFAULT '{}'::jsonb,
    tech_stack jsonb NOT NULL DEFAULT '[]'::jsonb,
    keywords jsonb NOT NULL DEFAULT '[]'::jsonb,
    body_is_image boolean NOT NULL DEFAULT false,
    required_majors jsonb NOT NULL DEFAULT '[]'::jsonb,
    required_major_terms jsonb NOT NULL DEFAULT '[]'::jsonb,
    required_certifications jsonb NOT NULL DEFAULT '[]'::jsonb,
    required_certification_groups jsonb NOT NULL DEFAULT '[]'::jsonb,
    required_language_tests jsonb NOT NULL DEFAULT '[]'::jsonb,
    military_required boolean NOT NULL DEFAULT false,
    preferred_majors jsonb NOT NULL DEFAULT '[]'::jsonb,
    preferred_major_terms jsonb NOT NULL DEFAULT '[]'::jsonb,
    preferred_certifications jsonb NOT NULL DEFAULT '[]'::jsonb,
    preferred_language_tests jsonb NOT NULL DEFAULT '[]'::jsonb,
    first_seen_at timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL,
    missing_runs integer NOT NULL DEFAULT 0,
    revisions integer NOT NULL DEFAULT 0,
    embed_hash varchar,
    indexed_embed_hash varchar,
    indexed_at timestamptz,
    group_key varchar
);
CREATE UNIQUE INDEX IF NOT EXISTS jobs_source_key ON jobs (source, source_job_id);
CREATE INDEX IF NOT EXISTS jobs_status ON jobs (status);
CREATE INDEX IF NOT EXISTS jobs_deadline ON jobs (deadline);
CREATE INDEX IF NOT EXISTS jobs_content_hash ON jobs (content_hash);
CREATE INDEX IF NOT EXISTS jobs_group ON jobs (group_key);

CREATE TABLE IF NOT EXISTS job_tags (
    job_id varchar NOT NULL REFERENCES jobs (job_id) ON DELETE CASCADE,
    kind varchar NOT NULL,
    value varchar NOT NULL,
    PRIMARY KEY (job_id, kind, value)
);
CREATE INDEX IF NOT EXISTS job_tags_kind_value ON job_tags (kind, value);

CREATE TABLE IF NOT EXISTS runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at timestamptz NOT NULL,
    finished_at timestamptz,
    source varchar,
    new integer,
    updated integer,
    unchanged integer,
    expired integer,
    removed integer,
    observed integer,
    still_missing integer,
    vectors integer,
    error text
);

CREATE TABLE IF NOT EXISTS list_seen (
    source_job_id varchar NOT NULL,
    cat_mcls varchar NOT NULL,
    seen_at timestamptz NOT NULL,
    first_seen_at timestamptz,
    source varchar NOT NULL DEFAULT 'SARAMIN_POC',
    PRIMARY KEY (source, source_job_id, cat_mcls)
);
CREATE INDEX IF NOT EXISTS list_seen_at ON list_seen (seen_at);
CREATE INDEX IF NOT EXISTS list_seen_job ON list_seen (source_job_id);

CREATE TABLE IF NOT EXISTS link_checks (
    job_id varchar PRIMARY KEY,
    checked_at timestamptz NOT NULL,
    alive boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS list_jobs (
    source_job_id varchar NOT NULL,
    job_id varchar NOT NULL,
    source_url varchar,
    company varchar,
    title varchar,
    keywords jsonb NOT NULL DEFAULT '[]'::jsonb,
    region varchar,
    career_type varchar,
    min_career_years integer,
    education varchar,
    employment_type varchar,
    condition_text text,
    deadline varchar,
    support_text varchar,
    seen_at timestamptz NOT NULL,
    first_seen_at timestamptz,
    source varchar NOT NULL DEFAULT 'SARAMIN_POC',
    PRIMARY KEY (source, source_job_id)
);
CREATE INDEX IF NOT EXISTS list_jobs_seen ON list_jobs (seen_at);
CREATE INDEX IF NOT EXISTS list_jobs_job ON list_jobs (source_job_id);

CREATE OR REPLACE VIEW list_jobs_search AS
SELECT
    source_job_id, job_id, source_url, company, title, keywords,
    region, career_type, min_career_years, education, employment_type,
    'OPEN'::varchar AS status,
    deadline,
    '[]'::jsonb AS tech_stack,
    ''::varchar AS description,
    seen_at, first_seen_at, source
FROM list_jobs;

CREATE TABLE IF NOT EXISTS list_sweeps (
    cat_mcls varchar PRIMARY KEY,
    swept_at timestamptz NOT NULL,
    total_count integer,
    seen integer
);
