-- 복습 문제(공부방 · 파이썬 연습장) — practice 스키마.
--
-- 적용:  psql -U postgres -d lms -f scripts/firestore_to_postgres/practice_schema.sql
--        (Docker) docker compose exec -T db psql -U postgres -d lms -f - < scripts/firestore_to_postgres/practice_schema.sql
-- 여러 번 실행해도 된다(IF NOT EXISTS).
--
-- 왜 public 이 아니라 practice 스키마인가
--   etl.py 는 돌 때마다 public 을 DROP ... CASCADE 하고 다시 만든다. 여기 두면 학생 풀이 기록이 같이 지워진다.
-- 왜 users.id · cohorts.id 를 외래키로 걸지 않는가
--   ETL 이 public 을 다시 만들면 users.id 가 새로 매겨진다. 숫자 id 로 가리키면 풀이 기록이 다른 학생에게 붙는다.
--   그래서 바뀌지 않는 값으로 가리킨다: 사용자는 users.firebase_uid, 기수는 cohorts.code.
--   (public 을 DROP CASCADE 하면 걸어 둔 외래키도 사라진다)
--
-- 문제 모양은 study_notes/practice/models.py 의 PracticeProblem.to_json() 과 같다.

BEGIN;

CREATE SCHEMA IF NOT EXISTS practice;

-- 수업 날짜별 복습 문제 묶음. 기수 공용.
CREATE TABLE IF NOT EXISTS practice.sets (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id    varchar NOT NULL UNIQUE,              -- 화면이 쓰는 세트 id (예: ps-mm-0915)
    cohort_code  varchar NOT NULL,                     -- cohorts.code
    source_title varchar NOT NULL DEFAULT '',          -- 수업 저장소 이름 (예: multimodal)
    lesson_date  date    NOT NULL,                     -- 수업 날짜
    day_label    varchar NOT NULL DEFAULT '',          -- 예: 멀티모달 3일차
    title        varchar NOT NULL DEFAULT '',
    files        jsonb   NOT NULL DEFAULT '[]',        -- 문제를 만든 수업 파일 경로들
    model        varchar NOT NULL DEFAULT '',          -- 만든 LLM (예: gpt-5.6-luna)
    created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS sets_cohort_date ON practice.sets (cohort_code, lesson_date DESC);

-- 세트 안의 문제. idx 는 세트 안 순서(0부터) — 화면의 문제 번호 - 1.
CREATE TABLE IF NOT EXISTS practice.problems (
    id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id             bigint  NOT NULL REFERENCES practice.sets (id) ON DELETE CASCADE,
    idx                int     NOT NULL,
    kind               varchar NOT NULL CHECK (kind IN ('concept', 'code_output', 'code_blank', 'code_fix', 'code_write')),
    topic              varchar NOT NULL DEFAULT '',
    prompt             text    NOT NULL DEFAULT '',
    source_files       jsonb   NOT NULL DEFAULT '[]',
    explanation        text    NOT NULL DEFAULT '',
    choices            jsonb   NOT NULL DEFAULT '[]',  -- concept 보기
    answer_index       int,                            -- concept 정답 보기 번호
    starter_code       text    NOT NULL DEFAULT '',
    expected_stdout    text    NOT NULL DEFAULT '',    -- code_output 정답 출력
    blank_answers      jsonb   NOT NULL DEFAULT '[]',  -- code_blank 빈칸 답
    reference_solution text    NOT NULL DEFAULT '',
    hidden_tests       text    NOT NULL DEFAULT '',    -- 채점용 assert 들 — 학생 화면에는 보이지 않는다
    packages           jsonb   NOT NULL DEFAULT '[]',
    UNIQUE (set_id, idx)
);

-- 학생별 풀이 기록. 한 문제에 한 줄 — 다시 풀면 tries 가 늘고 passed 가 바뀐다.
CREATE TABLE IF NOT EXISTS practice.attempts (
    user_uid    varchar NOT NULL,                      -- users.firebase_uid
    problem_id  bigint  NOT NULL REFERENCES practice.problems (id) ON DELETE CASCADE,
    passed      boolean NOT NULL,
    tries       int     NOT NULL DEFAULT 1,
    answered_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (user_uid, problem_id)
);
CREATE INDEX IF NOT EXISTS attempts_problem ON practice.attempts (problem_id);

-- 「이 문제 이상해요」 신고. 한 문제에 한 사람 한 번 — 다시 보내면 이유 · 메모가 바뀐다.
CREATE TABLE IF NOT EXISTS practice.reports (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uid   varchar NOT NULL,
    problem_id bigint  NOT NULL REFERENCES practice.problems (id) ON DELETE CASCADE,
    reason     varchar NOT NULL CHECK (reason IN ('unclear', 'answer', 'tests', 'offtopic', 'other')),
    note       text    NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (user_uid, problem_id)
);
CREATE INDEX IF NOT EXISTS reports_problem ON practice.reports (problem_id);

-- 강사 결정 — 없으면 신고 수로 판단(서로 다른 학생 2명이면 숨김). 있으면 이것이 우선.
CREATE TABLE IF NOT EXISTS practice.reviews (
    problem_id     bigint  PRIMARY KEY REFERENCES practice.problems (id) ON DELETE CASCADE,
    decision       varchar NOT NULL CHECK (decision IN ('hidden', 'kept')),
    decided_by_uid varchar NOT NULL,
    decided_at     timestamptz NOT NULL DEFAULT now()
);

-- 출제 범위 기록 — 수업 파일마다 어느 셀까지 문제로 냈는지(study_notes/practice/daily.py --coverage JSON 그대로).
-- 다음 날 문제를 새로 생긴 셀로만 내기 위해 쓴다.
CREATE TABLE IF NOT EXISTS practice.coverage (
    cohort_code  varchar NOT NULL,
    source_title varchar NOT NULL,
    data         jsonb   NOT NULL DEFAULT '{}',
    updated_at   timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (cohort_code, source_title)
);

COMMIT;
