-- LMS PostgreSQL schema (Notion ERD 초안). jobs 스키마와 youtube_curriculum_cache 는 제외.
-- posts / qna 는 운영 건수 0건이면 이 파일에서 테이블을 만들지 않는다.

BEGIN;

CREATE TABLE cohorts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar NOT NULL UNIQUE,
    name varchar NOT NULL,
    description text,
    term_number int,
    classroom_name varchar,
    status varchar NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    start_date date,
    end_date date,
    published_seating_room_id bigint,
    created_at timestamptz
);

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firebase_uid varchar UNIQUE,
    email varchar UNIQUE,
    password varchar NOT NULL DEFAULT '',
    personal_email varchar,
    display_name varchar NOT NULL DEFAULT '',
    role varchar NOT NULL,
    cohort_id bigint REFERENCES cohorts (id) ON DELETE RESTRICT,
    seat_number int,
    is_active boolean NOT NULL DEFAULT true,
    must_change_password boolean NOT NULL DEFAULT false,
    motto varchar,
    skills text[] NOT NULL DEFAULT '{}',
    social_links jsonb NOT NULL DEFAULT '{}',
    job_preferences jsonb NOT NULL DEFAULT '{}',
    birth_date date,
    photo_url varchar,
    photo_storage_path varchar,
    mileage_balance int NOT NULL DEFAULT 0,
    last_login timestamptz,
    created_at timestamptz,
    updated_at timestamptz
);

CREATE TABLE student_intakes (
    user_id bigint PRIMARY KEY REFERENCES users (id) ON DELETE RESTRICT,
    education_major varchar NOT NULL DEFAULT '',
    current_status varchar NOT NULL DEFAULT '',
    weekly_study_hours varchar NOT NULL DEFAULT '',
    programming_level varchar NOT NULL DEFAULT '',
    collaboration_tools varchar NOT NULL DEFAULT '',
    ai_llm_experience varchar NOT NULL DEFAULT '',
    motivation text NOT NULL DEFAULT '',
    desired_role text NOT NULL DEFAULT '',
    post_completion_goal text NOT NULL DEFAULT '',
    awards text NOT NULL DEFAULT '',
    project_links text NOT NULL DEFAULT '',
    team_role text NOT NULL DEFAULT '',
    self_learning_style text NOT NULL DEFAULT '',
    slump_overcome_experience text NOT NULL DEFAULT '',
    is_active boolean NOT NULL DEFAULT true,
    created_by bigint REFERENCES users (id) ON DELETE SET NULL,
    created_at timestamptz
);

CREATE TABLE todos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    title varchar NOT NULL,
    is_completed boolean NOT NULL DEFAULT false,
    created_at timestamptz
);

CREATE TABLE system_cache (
    key varchar PRIMARY KEY,
    data jsonb NOT NULL DEFAULT '{}',
    synced_at timestamptz
);

CREATE TABLE schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    date_key date NOT NULL,
    sessions jsonb NOT NULL DEFAULT '[]',
    current_session_index int,
    UNIQUE (cohort_id, date_key)
);

CREATE TABLE curriculum_pdfs (
    cohort_id bigint PRIMARY KEY REFERENCES cohorts (id) ON DELETE RESTRICT,
    full_pdf_url varchar,
    full_pdf_file_name varchar,
    published boolean NOT NULL DEFAULT false,
    updated_by bigint REFERENCES users (id) ON DELETE SET NULL,
    updated_at timestamptz
);

CREATE TABLE curriculum_sheets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    title varchar,
    file_name varchar,
    storage_path varchar,
    source varchar,
    uploaded_by bigint REFERENCES users (id) ON DELETE SET NULL,
    uploaded_at timestamptz
);
CREATE INDEX ON curriculum_sheets (cohort_id, uploaded_at DESC);

CREATE TABLE curriculum_rows (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sheet_id bigint NOT NULL REFERENCES curriculum_sheets (id) ON DELETE CASCADE,
    day_index int,
    date_label varchar,
    subject varchar,
    topic varchar,
    detail text,
    "order" int
);

CREATE TABLE materials (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    title varchar,
    file_url varchar,
    file_name varchar,
    description text,
    created_at timestamptz
);

CREATE TABLE attendances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    date_key date NOT NULL,
    status varchar,
    status_source varchar,
    check_in_time time,
    check_out_time time,
    form_attendance_type varchar,
    official_leave_used boolean,
    official_leave_type varchar,
    official_leave_other varchar,
    recorded_at timestamptz,
    UNIQUE (user_id, date_key)
);

CREATE TABLE roll_calls (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    date_key date NOT NULL,
    period_id varchar NOT NULL,
    carried_from_period_id varchar,
    updated_by bigint REFERENCES users (id) ON DELETE SET NULL,
    updated_at timestamptz,
    UNIQUE (cohort_id, date_key, period_id)
);

CREATE TABLE roll_call_entries (
    roll_call_id bigint NOT NULL REFERENCES roll_calls (id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    state varchar NOT NULL,
    PRIMARY KEY (roll_call_id, user_id)
);

CREATE TABLE seating_rooms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    room_number varchar,
    rows int,
    cols int,
    max_students int,
    updated_by bigint REFERENCES users (id) ON DELETE SET NULL,
    created_at timestamptz,
    updated_at timestamptz
);

ALTER TABLE cohorts
    ADD CONSTRAINT cohorts_published_seating_room_id_fkey
    FOREIGN KEY (published_seating_room_id) REFERENCES seating_rooms (id);

CREATE TABLE seating_cells (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id bigint NOT NULL REFERENCES seating_rooms (id) ON DELETE CASCADE,
    seat_id varchar NOT NULL,
    row int,
    col int,
    label varchar,
    type varchar NOT NULL,
    group_id varchar,
    UNIQUE (room_id, seat_id),
    UNIQUE (room_id, row, col)
);

CREATE TABLE seating_assignments (
    room_id bigint PRIMARY KEY REFERENCES seating_rooms (id) ON DELETE CASCADE,
    status varchar NOT NULL,
    published_at timestamptz,
    published_by bigint REFERENCES users (id) ON DELETE SET NULL,
    updated_at timestamptz,
    updated_by bigint REFERENCES users (id) ON DELETE SET NULL
);

CREATE TABLE seat_assignments (
    room_id bigint NOT NULL REFERENCES seating_assignments (room_id) ON DELETE CASCADE,
    cell_id bigint NOT NULL REFERENCES seating_cells (id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    PRIMARY KEY (room_id, cell_id),
    UNIQUE (room_id, user_id)
);

CREATE TABLE project_teams (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    name varchar,
    sort_order int,
    color_index int,
    updated_by bigint REFERENCES users (id) ON DELETE SET NULL,
    updated_at timestamptz
);

CREATE TABLE project_team_members (
    team_id bigint NOT NULL REFERENCES project_teams (id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    PRIMARY KEY (team_id, user_id)
);

CREATE TABLE scheduled_notices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    title varchar,
    content text,
    author_id bigint REFERENCES users (id) ON DELETE SET NULL,
    is_favorite boolean NOT NULL DEFAULT false,
    repeat_type varchar,
    publish_time time,
    publish_at timestamptz,
    weekday int,
    is_active boolean NOT NULL DEFAULT true,
    last_published_at timestamptz,
    next_publish_at timestamptz,
    created_at timestamptz,
    updated_at timestamptz
);
CREATE INDEX ON scheduled_notices (is_active, next_publish_at);

CREATE TABLE notices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    title varchar,
    content text,
    author_id bigint REFERENCES users (id) ON DELETE SET NULL,
    author_name varchar,
    is_favorite boolean NOT NULL DEFAULT false,
    priority int NOT NULL DEFAULT 0,
    source varchar,
    channel_label varchar,
    discord_message_id varchar UNIQUE,
    discord_channel_id varchar,
    discord_channel_type varchar,
    scheduled_notice_id bigint REFERENCES scheduled_notices (id) ON DELETE SET NULL,
    image_url varchar,
    vector_chunk_count int NOT NULL DEFAULT 0,
    created_at timestamptz,
    updated_at timestamptz
);

CREATE TABLE alert_popups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    title varchar,
    content text,
    author_id bigint REFERENCES users (id) ON DELETE SET NULL,
    is_active boolean NOT NULL DEFAULT true,
    sort_order int,
    link_url varchar,
    start_time time,
    end_time time,
    created_at timestamptz,
    updated_at timestamptz
);

CREATE TABLE alert_popup_dismissals (
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    popup_id bigint NOT NULL REFERENCES alert_popups (id) ON DELETE CASCADE,
    date_key date,
    PRIMARY KEY (user_id, popup_id)
);

CREATE TABLE assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    title varchar,
    description text,
    due_date timestamptz,
    created_at timestamptz
);

CREATE TABLE assignment_submissions (
    assignment_id bigint NOT NULL REFERENCES assignments (id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    file_url varchar,
    file_name varchar,
    file_size_bytes bigint,
    status varchar,
    submitted_at timestamptz,
    PRIMARY KEY (assignment_id, user_id)
);

CREATE TABLE record_submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    type varchar NOT NULL,
    status varchar NOT NULL,
    title varchar,
    review_comment text,
    reviewed_by bigint REFERENCES users (id) ON DELETE SET NULL,
    reviewed_at timestamptz,
    cert_type varchar,
    file_urls text[] NOT NULL DEFAULT '{}',
    start_at timestamptz,
    end_at timestamptz,
    week_number int,
    week_label varchar,
    link varchar,
    quiz_score int,
    learning_date date,
    learning_content text,
    is_team_study boolean,
    mileage_granted boolean NOT NULL DEFAULT false,
    mileage_amount int NOT NULL DEFAULT 0,
    submitted_at timestamptz
);

CREATE TABLE weekly_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    title varchar,
    due_date timestamptz,
    total_count int
);

CREATE TABLE weekly_progress (
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    completed_count int NOT NULL DEFAULT 0,
    total_count int NOT NULL DEFAULT 0,
    updated_at timestamptz,
    PRIMARY KEY (cohort_id, user_id)
);

CREATE TABLE form_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    title varchar,
    description text,
    form_url varchar,
    notion_guide_url varchar,
    due_at timestamptz,
    published boolean NOT NULL DEFAULT true,
    created_at timestamptz,
    updated_at timestamptz
);

CREATE TABLE form_responses (
    task_id bigint NOT NULL REFERENCES form_tasks (id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    source varchar,
    google_response_id varchar UNIQUE,
    submitted_at timestamptz,
    PRIMARY KEY (task_id, user_id)
);

CREATE TABLE ai_generation_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    type varchar,
    cohort_id bigint REFERENCES cohorts (id) ON DELETE RESTRICT,
    created_by bigint REFERENCES users (id) ON DELETE SET NULL,
    prompt_version varchar,
    model varchar,
    status varchar,
    error_message text,
    latency_ms int,
    token_in int,
    token_out int,
    details jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz
);
CREATE INDEX ON ai_generation_logs (type, created_at DESC);

CREATE TABLE assessments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    title varchar,
    tags text[] NOT NULL DEFAULT '{}',
    max_score int,
    start_at timestamptz,
    end_at timestamptz,
    thumbnail_url varchar,
    thumbnail_path varchar,
    published boolean NOT NULL DEFAULT false,
    created_by bigint REFERENCES users (id) ON DELETE SET NULL,
    created_at timestamptz,
    updated_at timestamptz,
    curriculum_sheet_id bigint REFERENCES curriculum_sheets (id) ON DELETE SET NULL,
    day_from int,
    day_to int,
    subject_filter varchar
);

CREATE TABLE assessment_questions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    assessment_id bigint NOT NULL REFERENCES assessments (id) ON DELETE CASCADE,
    "order" int,
    type varchar,
    prompt text,
    points int,
    choices text[] NOT NULL DEFAULT '{}',
    correct_index int,
    accepted_answers text[] NOT NULL DEFAULT '{}',
    explanation text,
    origin varchar,
    ai_log_id bigint REFERENCES ai_generation_logs (id) ON DELETE SET NULL,
    ai_draft_id varchar,
    prompt_version varchar,
    source_day int,
    source_topic varchar
);

CREATE TABLE assessment_submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    assessment_id bigint NOT NULL REFERENCES assessments (id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    auto_total_score int,
    total_score int,
    status varchar,
    submitted_at timestamptz,
    UNIQUE (assessment_id, user_id)
);

CREATE TABLE assessment_answers (
    submission_id bigint NOT NULL REFERENCES assessment_submissions (id) ON DELETE CASCADE,
    question_id bigint NOT NULL REFERENCES assessment_questions (id) ON DELETE CASCADE,
    value jsonb,
    auto_score int,
    final_score int,
    is_correct boolean,
    PRIMARY KEY (submission_id, question_id)
);

CREATE TABLE assessment_score_adjustments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id bigint NOT NULL REFERENCES assessment_submissions (id) ON DELETE CASCADE,
    question_id bigint REFERENCES assessment_questions (id) ON DELETE SET NULL,
    previous int,
    next int,
    adjusted_by bigint REFERENCES users (id) ON DELETE SET NULL,
    adjusted_at timestamptz,
    note text
);

CREATE TABLE mileage_transactions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    amount int NOT NULL,
    reason varchar,
    type varchar,
    related_id varchar,
    adjusted_by bigint REFERENCES users (id) ON DELETE SET NULL,
    created_at timestamptz
);

CREATE TABLE mileage_settings (
    cohort_id bigint PRIMARY KEY REFERENCES cohorts (id) ON DELETE RESTRICT,
    category_limits jsonb NOT NULL DEFAULT '{}',
    accrual_rules jsonb NOT NULL DEFAULT '{}',
    updated_by bigint REFERENCES users (id) ON DELETE SET NULL,
    updated_at timestamptz
);

CREATE TABLE mileage_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    name varchar,
    description text,
    image_url varchar,
    category varchar,
    pricing_type varchar,
    fixed_price int,
    is_active boolean NOT NULL DEFAULT true,
    sort_order int,
    created_at timestamptz,
    updated_at timestamptz
);

CREATE TABLE purchase_requests (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    total_amount int,
    status varchar,
    student_note text,
    manager_memo text,
    manager_purchase_link varchar,
    processed_by bigint REFERENCES users (id) ON DELETE SET NULL,
    processed_at timestamptz,
    created_at timestamptz,
    updated_at timestamptz
);

CREATE TABLE purchase_request_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id bigint NOT NULL REFERENCES purchase_requests (id) ON DELETE CASCADE,
    product_id bigint REFERENCES mileage_products (id) ON DELETE SET NULL,
    product_name varchar,
    category varchar,
    pricing_type varchar,
    unit_price int,
    quantity int,
    purchase_link varchar
);

CREATE TABLE mileage_cart_items (
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    product_id bigint NOT NULL REFERENCES mileage_products (id) ON DELETE CASCADE,
    quantity int NOT NULL DEFAULT 1,
    unit_price int,
    purchase_link varchar,
    updated_at timestamptz,
    PRIMARY KEY (user_id, product_id)
);

CREATE TABLE mission_progress (
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    study_cert_count int NOT NULL DEFAULT 0,
    study_cert_granted int NOT NULL DEFAULT 0,
    quiz_pass_count int NOT NULL DEFAULT 0,
    quiz_granted int NOT NULL DEFAULT 0,
    coding_pcce boolean NOT NULL DEFAULT false,
    coding_pccp boolean NOT NULL DEFAULT false,
    coding_pcsql boolean NOT NULL DEFAULT false,
    coding_granted int NOT NULL DEFAULT 0,
    blog_weeks int[] NOT NULL DEFAULT '{}',
    blog_units_granted int[] NOT NULL DEFAULT '{}',
    study_week_keys text[] NOT NULL DEFAULT '{}',
    study_granted boolean NOT NULL DEFAULT false,
    updated_at timestamptz,
    PRIMARY KEY (cohort_id, user_id)
);

CREATE TABLE resumes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    title varchar,
    status varchar,
    content jsonb NOT NULL DEFAULT '{}',
    sections jsonb NOT NULL DEFAULT '{}',
    is_base_resume boolean NOT NULL DEFAULT false,
    base_resume_id bigint REFERENCES resumes (id) ON DELETE SET NULL,
    source_tailored_resume_id bigint REFERENCES resumes (id) ON DELETE SET NULL,
    linked_job_id varchar,
    created_at timestamptz,
    updated_at timestamptz
);

CREATE TABLE resume_feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    resume_id bigint NOT NULL REFERENCES resumes (id) ON DELETE CASCADE,
    parent_id bigint REFERENCES resume_feedback (id) ON DELETE SET NULL,
    section_key varchar,
    content text,
    author_id bigint REFERENCES users (id) ON DELETE SET NULL,
    created_at timestamptz
);

CREATE TABLE resume_feedback_reads (
    feedback_id bigint NOT NULL REFERENCES resume_feedback (id) ON DELETE CASCADE,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    read_at timestamptz,
    PRIMARY KEY (feedback_id, user_id)
);

CREATE TABLE resume_revisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    resume_id bigint NOT NULL REFERENCES resumes (id) ON DELETE CASCADE,
    title varchar,
    content jsonb NOT NULL DEFAULT '{}',
    saved_at timestamptz
);

CREATE TABLE inflearn_packages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    title varchar,
    subject varchar,
    type varchar,
    summary text,
    units jsonb NOT NULL DEFAULT '[]',
    courses jsonb NOT NULL DEFAULT '[]',
    is_published boolean NOT NULL DEFAULT false,
    sort_order int,
    published_at timestamptz,
    created_at timestamptz,
    updated_at timestamptz
);

CREATE TABLE youtube_recommendations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    video_id varchar,
    title varchar,
    youtube_url varchar,
    thumbnail_url varchar,
    description text,
    tags text[] NOT NULL DEFAULT '{}',
    is_published boolean NOT NULL DEFAULT false,
    sort_order int,
    created_at timestamptz,
    updated_at timestamptz,
    UNIQUE (cohort_id, video_id)
);

CREATE TABLE recommendation_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    user_id bigint REFERENCES users (id) ON DELETE SET NULL,
    recommendation_id bigint REFERENCES youtube_recommendations (id) ON DELETE SET NULL,
    youtube_video_id varchar,
    user_skills text[] NOT NULL DEFAULT '{}',
    matched_tags text[] NOT NULL DEFAULT '{}',
    action varchar,
    created_at timestamptz
);

CREATE TABLE study_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    cohort_id bigint NOT NULL REFERENCES cohorts (id) ON DELETE RESTRICT,
    title varchar,
    repo_url varchar,
    branch varchar,
    allowed_prefixes text[] NOT NULL DEFAULT '{}',
    is_active boolean NOT NULL DEFAULT true,
    sort_order int,
    created_at timestamptz,
    updated_at timestamptz
);

CREATE TABLE study_notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    user_id bigint NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
    source_id bigint REFERENCES study_sources (id) ON DELETE SET NULL,
    status varchar,
    scope_type varchar,
    scope_value jsonb,
    scope_key varchar,
    report_markdown text,
    review_markdown text,
    error_message text,
    message text,
    files jsonb NOT NULL DEFAULT '[]',
    created_at timestamptz
);

CREATE TABLE ai_question_feedback (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    log_id bigint REFERENCES ai_generation_logs (id) ON DELETE SET NULL,
    draft_id varchar,
    cohort_id bigint REFERENCES cohorts (id) ON DELETE RESTRICT,
    outcome varchar,
    type varchar,
    prompt_version varchar,
    assessment_id bigint REFERENCES assessments (id) ON DELETE SET NULL,
    question_id bigint REFERENCES assessment_questions (id) ON DELETE SET NULL,
    source_day int,
    source_topic varchar,
    actor_id bigint REFERENCES users (id) ON DELETE SET NULL,
    created_at timestamptz,
    updated_at timestamptz
);

CREATE TABLE ai_eval_runs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    prompt_version varchar,
    model varchar,
    source varchar,
    total_cases int,
    passed int,
    accuracy numeric,
    avg_latency_ms int,
    failed_ids text[] NOT NULL DEFAULT '{}',
    created_at timestamptz
);

-- 미매핑 3컬렉션 (cover_letter_rag 필드 그대로)
CREATE TABLE job_requirement_profiles (
    key varchar PRIMARY KEY,
    requirements jsonb NOT NULL DEFAULT '[]',
    created_at timestamptz
);

CREATE TABLE resume_ai_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    resume_id bigint NOT NULL REFERENCES resumes (id) ON DELETE CASCADE,
    user_id bigint REFERENCES users (id) ON DELETE SET NULL,
    fingerprint varchar,
    status varchar,
    response jsonb,
    telemetry jsonb,
    payload jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz
);

CREATE TABLE resume_ai_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    resume_id bigint NOT NULL REFERENCES resumes (id) ON DELETE CASCADE,
    user_id bigint REFERENCES users (id) ON DELETE SET NULL,
    fingerprint varchar,
    kind varchar,
    before jsonb,
    after_hash varchar,
    response jsonb,
    source_id varchar,
    undone_by varchar,
    payload jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz
);

COMMIT;
