-- Apply to an existing lms DB. Does NOT drop public.
CREATE TABLE IF NOT EXISTS job_requirement_profiles (
    key varchar PRIMARY KEY,
    requirements jsonb NOT NULL DEFAULT '[]',
    created_at timestamptz
);

CREATE TABLE IF NOT EXISTS resume_ai_reviews (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    resume_id bigint NOT NULL REFERENCES resumes (id) ON DELETE CASCADE,
    user_id bigint REFERENCES users (id) ON DELETE SET NULL,
    fingerprint varchar,
    status varchar,
    response jsonb,
    telemetry jsonb,
    payload jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz
);

CREATE TABLE IF NOT EXISTS resume_ai_applications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legacy_id varchar UNIQUE,
    resume_id bigint NOT NULL REFERENCES resumes (id) ON DELETE CASCADE,
    user_id bigint REFERENCES users (id) ON DELETE SET NULL,
    fingerprint varchar,
    kind varchar,
    before jsonb,
    after_hash varchar,
    response jsonb,
    source_id varchar,
    undone_by varchar,
    payload jsonb NOT NULL DEFAULT '{}',
    created_at timestamptz
);
