-- 공부방 수업 저장소 자동 등록 — study 스키마.
--
-- 적용:  psql -U postgres -d lms -f scripts/firestore_to_postgres/study_schema.sql
--        (Docker) docker compose exec -T db psql -U postgres -d lms -f - < scripts/firestore_to_postgres/study_schema.sql
-- 여러 번 실행해도 된다(IF NOT EXISTS).
--
-- 기수마다 GitHub 조직·계정을 연결해 두면, 그 안의 저장소를 public.study_sources 에 자동으로 올린다(바로 공개).
-- 강사·관리자는 숨기기만 하면 된다. 숨긴 저장소는 다시 찾아도 숨긴 채로 둔다.
--
-- 왜 public 이 아니라 study 스키마인가 — practice 스키마와 같은 이유. etl.py 가 public 을 지우고 다시 만든다.
-- 연결 목록이 여기 남아 있으면, ETL 뒤 study_sources 가 비어도 다음 찾기에서 저장소가 다시 채워진다.
-- 기수는 cohorts.code 로 가리킨다(ETL 이 cohorts.id 를 새로 매긴다).

BEGIN;

CREATE SCHEMA IF NOT EXISTS study;

-- 기수에 연결한 GitHub 조직 또는 계정(강사 개인 계정 포함)
CREATE TABLE IF NOT EXISTS study.github_owners (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_code    varchar NOT NULL,                     -- cohorts.code
    owner          varchar NOT NULL,                     -- GitHub 조직·계정 이름 (예: skn-ai34-260616)
    added_by_uid   varchar NOT NULL DEFAULT '',          -- users.firebase_uid
    last_synced_at timestamptz,                          -- 마지막으로 저장소를 찾은 때
    last_error     text    NOT NULL DEFAULT '',          -- 그때 실패했다면 이유
    created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS github_owners_cohort_owner ON study.github_owners (cohort_code, lower(owner));

COMMIT;
