-- 공부방 수업 저장소 자동 등록 — study 스키마.
--
-- 적용:  psql -U postgres -d lms -f scripts/firestore_to_postgres/study_schema.sql
--        (Docker) docker compose exec -T db psql -U postgres -d lms -f - < scripts/firestore_to_postgres/study_schema.sql
-- 여러 번 실행해도 된다(IF NOT EXISTS).
--
-- 기수마다 GitHub 조직·계정을 연결해 두면, 그 안의 저장소를 public.study_sources 에 자동으로 올린다(바로 공개).
-- 강사·관리자는 숨기기만 하면 된다. 숨긴 저장소는 다시 찾아도 숨긴 채로 둔다.
--
-- 왜 public 이 아니라 study 스키마인가 — practice 스키마와 같은 이유. etl.py 가 public 을 지우고 다시 만든다.
-- 연결 목록이 여기 남아 있으면, ETL 뒤 study_sources 가 비어도 다음 찾기에서 저장소가 다시 채워진다.
-- 기수는 cohorts.code 로 가리킨다(ETL 이 cohorts.id 를 새로 매긴다).

BEGIN;

CREATE SCHEMA IF NOT EXISTS study;

-- 기수에 연결한 GitHub 조직 또는 계정(강사 개인 계정 포함)
CREATE TABLE IF NOT EXISTS study.github_owners (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_code    varchar NOT NULL,                     -- cohorts.code
    owner          varchar NOT NULL,                     -- GitHub 조직·계정 이름 (예: skn-ai34-260616)
    added_by_uid   varchar NOT NULL DEFAULT '',          -- users.firebase_uid
    last_synced_at timestamptz,                          -- 마지막으로 저장소를 찾은 때
    last_error     text    NOT NULL DEFAULT '',          -- 그때 실패했다면 이유
    created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS github_owners_cohort_owner ON study.github_owners (cohort_code, lower(owner));

-- 복습 문제 자동 출제 — 저장소마다 켜고 끈다. 줄이 없으면 켜짐(기본).
-- 저장소는 study_sources.id 대신 주소로 가리킨다(ETL 이 study_sources 를 다시 만들어도 이어지게).
CREATE TABLE IF NOT EXISTS study.practice_settings (
    cohort_code    varchar NOT NULL,
    repo_key       varchar NOT NULL,                     -- 저장소 주소 소문자, 끝 / · .git 뺀 것
    enabled        boolean NOT NULL DEFAULT true,
    updated_by_uid varchar NOT NULL DEFAULT '',
    updated_at     timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (cohort_code, repo_key)
);

-- 자동 출제를 돌린 기록 — 강사 화면의 「마지막 출제」와 같은 저장소를 두 번 동시에 돌리지 않는 데 쓴다
CREATE TABLE IF NOT EXISTS study.practice_runs (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_code varchar NOT NULL,
    repo_key    varchar NOT NULL,
    trigger     varchar NOT NULL DEFAULT 'schedule',     -- schedule(매일 18:30) · manual(지금 만들기)
    status      varchar NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'done', 'failed')),
    problems    int     NOT NULL DEFAULT 0,              -- 이번에 새로 낸 문제 수
    dates       jsonb   NOT NULL DEFAULT '[]',           -- 이번에 문제를 낸 수업 날짜
    message     text    NOT NULL DEFAULT '',
    started_at  timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz
);
CREATE INDEX IF NOT EXISTS practice_runs_repo ON study.practice_runs (cohort_code, repo_key, started_at DESC);

-- 학생이 노트 · 연습장 파일로 문제를 만드는 일 — 몇 분 걸려서 화면이 이 줄로 끝났는지 본다. 하루 몇 번까지인지도 여기서 센다
CREATE TABLE IF NOT EXISTS study.practice_jobs (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uid      varchar NOT NULL,                      -- users.firebase_uid
    cohort_code   varchar NOT NULL DEFAULT '',
    origin        varchar NOT NULL CHECK (origin IN ('note', 'file')),
    label         varchar NOT NULL DEFAULT '',           -- 화면에 보일 이름 (예: 09/15 수업 노트, lesson.ipynb)
    status        varchar NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'done', 'failed')),
    set_legacy_id varchar,                               -- 만든 세트(practice.sets.legacy_id)
    message       text    NOT NULL DEFAULT '',
    created_at    timestamptz NOT NULL DEFAULT now(),
    finished_at   timestamptz
);
CREATE INDEX IF NOT EXISTS practice_jobs_user ON study.practice_jobs (user_uid, created_at DESC);

COMMIT;
