/// 이력서/프로필 스킬 선택 카탈로그
abstract final class SkillCatalog {
  static const pageSize = 20;

  static const all = [
    '.NET',
    'Agile',
    'Android',
    'Angular',
    'Apache',
    'AWS',
    'Azure',
    'Bash',
    'Bootstrap',
    'C',
    'C#',
    'C++',
    'CI/CD',
    'CSS',
    'Dart',
    'Django',
    'Docker',
    'Elasticsearch',
    'Express.js',
    'FastAPI',
    'Figma',
    'Firebase',
    'Flask',
    'Flutter',
    'GCP',
    'Git',
    'GitHub Actions',
    'Go',
    'GraphQL',
    'Hadoop',
    'HTML',
    'Java',
    'JavaScript',
    'Jenkins',
    'JPA',
    'jQuery',
    'JSP',
    'JUnit',
    'Kafka',
    'Kotlin',
    'Kubernetes',
    'Linux',
    'Machine Learning',
    'MongoDB',
    'MyBatis',
    'MySQL',
    'NestJS',
    'Next.js',
    'Node.js',
    'Nuxt.js',
    'Objective-C',
    'OpenCV',
    'Oracle',
    'Pandas',
    'PHP',
    'PostgreSQL',
    'Power BI',
    'Python',
    'PyTorch',
    'R',
    'React',
    'React Native',
    'Redis',
    'REST API',
    'Ruby',
    'Ruby on Rails',
    'Rust',
    'Sass',
    'Scala',
    'Scikit-learn',
    'Scrum',
    'Shell Script',
    'Solidity',
    'Spark',
    'Spring',
    'Spring Boot',
    'SQL',
    'SQLite',
    'Supabase',
    'Svelte',
    'Swift',
    'Tailwind CSS',
    'TensorFlow',
    'Terraform',
    'TypeScript',
    'Unity',
    'Unreal Engine',
    'Vue.js',
    'WebRTC',
    'Webpack',
    'WordPress',
    'Zustand',
    '객체지향',
    '데이터 분석',
    '데이터베이스',
    '딥러닝',
    '모바일 개발',
    '백엔드',
    '보안',
    '알고리즘',
    '웹 개발',
    '인공지능',
    '자료구조',
    '프론트엔드',
    'Linux Server',
    'Microservices',
    'NoSQL',
    'OAuth',
    'ORM',
    'RESTful',
    'SaaS',
    'TDD',
    'UI/UX',
    'WebSocket',
    'XML',
    'YAML',
    'Airflow',
    'Ansible',
    'Apollo',
    'ArgoCD',
    'Assembly',
    'Blockchain',
    'Cassandra',
    'Cloudflare',
    'Cypress',
    'D3.js',
    'DDD',
    'DevOps',
    'Electron',
    'Ember.js',
    'Ethereum',
    'Expo',
    'Gatsby',
    'Gin',
    'Gradle',
    'gRPC',
    'Hibernate',
    'Hive',
    'HTTP/HTTPS',
    'Ionic',
    'Jest',
    'Jira',
    'JWT',
    'Keras',
    'Kibana',
    'Laravel',
    'LLM',
    'MLOps',
    'MobX',
    'MVC',
    'Nginx',
    'NLP',
    'NumPy',
    'OpenAPI',
    'OpenGL',
    'PWA',
    'RabbitMQ',
    'Redux',
    'Riverpod',
    'RxJava',
    'RxJS',
    'Selenium',
    'Serverless',
    'Socket.io',
    'Storybook',
    'Stripe',
    'SWR',
    'Three.js',
    'Tomcat',
    'Turborepo',
    'Vite',
    'WebAssembly',
    'WebGL',
    'Xamarin',
    'Zeppelin',
  ];

  static List<String> search(String query) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return List.from(all);
    return all.where((s) => s.toLowerCase().contains(q)).toList();
  }

  static int totalPages(List<String> filtered) {
    if (filtered.isEmpty) return 1;
    return (filtered.length / pageSize).ceil();
  }

  static List<String> pageItems(List<String> filtered, int page) {
    final start = page * pageSize;
    if (start >= filtered.length) return [];
    final end = (start + pageSize).clamp(0, filtered.length);
    return filtered.sublist(start, end);
  }
}
